In [ ]:
!pip install transformers trl accelerate torch bitsandbytes peft datasets -qU

/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [ ]:
import os
os.environ['HF_TOKEN'] = "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"

In [ ]:
from datasets import load_dataset

instruct_tune_dataset = load_dataset("FinGPT/fingpt-sentiment-train")
instruct_tune_dataset

type(instruct_tune_dataset)


datasets.dataset_dict.DatasetDict

In [ ]:
instruct_tune_dataset["train"]

Dataset({
    features: ['input', 'output', 'instruction'],
    num_rows: 76772
})

In [ ]:
instruct_tune_dataset["test"] = instruct_tune_dataset["train"].select(range(3000, 4500))
instruct_tune_dataset["train"] = instruct_tune_dataset["train"].select(range(3000))

In [ ]:
instruct_tune_dataset["train"][0]

{'input': 'Teollisuuden Voima Oyj , the Finnish utility known as TVO , said it shortlisted Mitsubishi Heavy s EU-APWR model along with reactors from Areva , Toshiba Corp. , GE Hitachi Nuclear Energy and Korea Hydro & Nuclear Power Co. .',
 'output': 'neutral',
 'instruction': 'What is the sentiment of this news? Please choose an answer from {negative/neutral/positive}.'}

In [ ]:
instruct_tune_dataset["test"][0]

{'input': 'Hedge Funds Are Dumping Ocwen Financial Corporation (OCN)',
 'output': 'negative',
 'instruction': 'What is the sentiment of this tweet? Please choose an answer from {negative/neutral/positive}.'}

In [ ]:
def create_prompt(sample):
    bos_token = "<s>"
    original_system_message = "Below is an instruction that describes a task. Write a response that appropriately completes the request."
    system_message = "Use the provided input, response to generate the response with an LLM."
    input = sample["input"]
    eos_token = "</s>"

    full_prompt = ""
    full_prompt += bos_token
    full_prompt += "\n" + original_system_message + "\n" + system_message + "\n"
    full_prompt += "### Instruction:"
    full_prompt += "\n" + sample['instruction']
    full_prompt += "\n\n### Input:"
    full_prompt += "\n" + sample['input']
    full_prompt += "\n\n### Response:"
    full_prompt += "\n" + sample['output']
    full_prompt += eos_token

    return full_prompt

In [ ]:
create_prompt(instruct_tune_dataset["train"][0])

'<s>\nBelow is an instruction that describes a task. Write a response that appropriately completes the request.\nUse the provided input, response to generate the response with an LLM.\n### Instruction:\nWhat is the sentiment of this news? Please choose an answer from {negative/neutral/positive}.\n\n### Input:\nTeollisuuden Voima Oyj , the Finnish utility known as TVO , said it shortlisted Mitsubishi Heavy s EU-APWR model along with reactors from Areva , Toshiba Corp. , GE Hitachi Nuclear Energy and Korea Hydro & Nuclear Power Co. .\n\n### Response:\nneutral</s>'

In [ ]:
import torch
from transformers import BitsAndBytesConfig
nf4_config = BitsAndBytesConfig(
   load_in_4bit=True,
   bnb_4bit_quant_type="nf4",
   bnb_4bit_use_double_quant=True,
   bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained(
    "mistralai/Mistral-7B-Instruct-v0.1",
    device_map='auto',
    quantization_config=nf4_config,
    use_cache=False
)

tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1")

tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import Trainer, TrainingArguments

peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM"
)

model = prepare_model_for_kbit_training(model)
model = get_peft_model(model, peft_config)

In [ ]:
args = TrainingArguments(
  output_dir = "mistral_instruct_generation",
#   num_train_epochs=1,
  max_steps = 50,
  per_device_train_batch_size = 8,
  warmup_steps = 3,
  logging_steps=10,
  save_strategy="epoch",
#   evaluation_strategy="epoch",
  evaluation_strategy="steps",
  eval_steps=10,
  learning_rate=2e-4,
  bf16=True,
  lr_scheduler_type='constant',
)

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [ ]:
max_seq_length = 256
from trl import SFTConfig, SFTTrainer
trainer = SFTTrainer(
  model=model,
  peft_config=peft_config,
  max_seq_length=max_seq_length,
  tokenizer=tokenizer,
  packing=True,
  formatting_func=create_prompt,
  args=args,
  train_dataset=instruct_tune_dataset["train"],
  eval_dataset=instruct_tune_dataset["test"]
)

/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length, packing. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:192: UserWarning: You passed a `packing` argument to the SFTTrainer, the value you passed will override the one in the `SFTConfig`.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:280: UserWarning: You passed a `max_seq_length` argument to the SFTTrainer, the value you passed will override the one in the `S

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

max_steps is given, it will override any value given in num_train_epochs
/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:432: UserWarning: You passed `packing=True` to the SFTTrainer/SFTConfig, and you are training your model with `max_steps` strategy. The dataset will be iterated until the `max_steps` are reached.
  warnings.warn(


In [ ]:
import time
start = time.time()
trainer.train()
print(time.time()- start)

/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]


3269.8657557964325


In [ ]:
trainer.save_model("mistral_instruct_generation")

In [ ]:
instruct_tune_dataset_1 = load_dataset("FinGPT/fingpt-sentiment-train")

generate_response(create_prompt(instruct_tune_dataset_1['train'][6000]), model)

NameError: name 'generate_response' is not defined

In [ ]:
from transformers import logging, pipeline
logging.set_verbosity(logging.CRITICAL)
pipe = pipeline(task="text-generation", model=model, tokenizer=tokenizer, max_length=256)

In [ ]:
def build_prompt(sample):
    bos_token = "<s>"
    original_system_message = "Below is an instruction that describes a task. Write a response that appropriately completes the request."
    system_message = "Use the provided input to generate the response with an LLM."
    input = sample["input"]
    eos_token = "</s>"

    full_prompt = ""
    full_prompt += bos_token
#     full_prompt += "\n" + original_system_message + "\n" + system_message + "\n"
    full_prompt += "### Instruction:"
    full_prompt += "\n" + sample['instruction']
    full_prompt += "\n\n### Input:"
    full_prompt += "\n" + sample['input']
    full_prompt += "\n\n### Response"
#     full_prompt += "\n" + sample['output']
#     full_prompt += eos_token

    return full_prompt
question = instruct_tune_dataset_1['train'][6000]
prompt = build_prompt(question)
result = pipe(prompt)

print(result[0]['generated_text'], " ,correct answer->", question['output'])

<s>### Instruction:
What is the sentiment of this news? Please choose an answer from {strong negative/moderately negative/mildly negative/neutral/mildly positive/moderately positive/strong positive}.

### Input:
Starbucks, a $124.4 billion company, trails only McDonald's as the largest restaurant chain by market capitalization. In this video, WSJ's Heather Haddon explains how Starbucks used technology to garner its loyal customer base and why mobile orders are shifting the chain's business priorities.

### Response:
neutral  ,correct answer-> mildly positive


In [ ]:
result[0]['generated_text'].split('Response:')[-1].replace("\n","")

'neutral'

In [ ]:
import pandas as pd

# Initialize an empty DataFrame
results = pd.DataFrame(columns=['Text', 'Actual', 'Prediction'])

# Iterate over the range of indices
for qi in range(6000, 6050):
    question = instruct_tune_dataset_1['train'][qi]
    prompt = build_prompt(question)
    result = pipe(prompt)
    pred = result[0]['generated_text'].split('Response:')[-1].replace("\n","")
    actual = question['output']

    # Create a new DataFrame for the current iteration
    new_row = pd.DataFrame({'Text': [prompt], 'Actual': [actual], 'Prediction': [pred]})

    # Concatenate the new row with the results DataFrame
    results = pd.concat([results, new_row], ignore_index=True)

# Display the results DataFrame
results

Text               Actual  \
0   <s>### Instruction:\nWhat is the sentiment of ...      mildly positive   
1   <s>### Instruction:\nWhat is the sentiment of ...             negative   
2   <s>### Instruction:\nWhat is the sentiment of ...             negative   
3   <s>### Instruction:\nWhat is the sentiment of ...  moderately negative   
4   <s>### Instruction:\nWhat is the sentiment of ...             positive   
5   <s>### Instruction:\nWhat is the sentiment of ...      strong positive   
6   <s>### Instruction:\nWhat is the sentiment of ...              neutral   
7   <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
8   <s>### Instruction:\nWhat is the sentiment of ...              neutral   
9   <s>### Instruction:\nWhat is the sentiment of ...      mildly positive   
10  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
11  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
12  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
13  <s>### Instruction:\nWhat is the sentiment of ...             positive   
14  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
15  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
16  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
17  <s>### Instruction:\nWhat is the sentiment of ...             negative   
18  <s>### Instruction:\nWhat is the sentiment of ...             positive   
19  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
20  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
21  <s>### Instruction:\nWhat is the sentiment of ...  moderately negative   
22  <s>### Instruction:\nWhat is the sentiment of ...             positive   
23  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
24  <s>### Instruction:\nWhat is the sentiment of ...             positive   
25  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
26  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
27  <s>### Instruction:\nWhat is the sentiment of ...             positive   
28  <s>### Instruction:\nWhat is the sentiment of ...             positive   
29  <s>### Instruction:\nWhat is the sentiment of ...             positive   
30  <s>### Instruction:\nWhat is the sentiment of ...             positive   
31  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
32  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
33  <s>### Instruction:\nWhat is the sentiment of ...             negative   
34  <s>### Instruction:\nWhat is the sentiment of ...             positive   
35  <s>### Instruction:\nWhat is the sentiment of ...             positive   
36  <s>### Instruction:\nWhat is the sentiment of ...  moderately positive   
37  <s>### Instruction:\nWhat is the sentiment of ...             positive   
38  <s>### Instruction:\nWhat is the sentiment of ...             positive   
39  <s>### Instruction:\nWhat is the sentiment of ...             positive   
40  <s>### Instruction:\nWhat is the sentiment of ...  moderately negative   
41  <s>### Instruction:\nWhat is the sentiment of ...  moderately negative   
42  <s>### Instruction:\nWhat is the sentiment of ...             negative   
43  <s>### Instruction:\nWhat is the sentiment of ...             negative   
44  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
45  <s>### Instruction:\nWhat is the sentiment of ...      mildly positive   
46  <s>### Instruction:\nWhat is the sentiment of ...              neutral   
47  <s>### Instruction:\nWhat is the sentiment of ...             negative   
48  <s>### Instruction:\nWhat is the sentiment of ...  moderately negative   
49  <s>### Instruction:\nWhat is the sentiment of ...              neutral   

             Prediction  
0               neutral  
1               ne

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

# Assuming your DataFrame `results` has columns 'Actual' and 'Prediction'
# Replace 'results' with your actual DataFrame if named differently

# Generate the confusion matrix
conf_matrix = confusion_matrix(results['Actual'], results['Prediction'])

# Calculate evaluation metrics: precision, recall, F1-score, etc.
report = classification_report(results['Actual'], results['Prediction'], output_dict=True)

# Convert the classification report to a DataFrame for better readability
report_df = pd.DataFrame(report).transpose()

# Display the confusion matrix and the classification report
print("Confusion Matrix:")
print(conf_matrix)

print("\nClassification Report:")
print(report_df)


Confusion Matrix:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0]
 [ 1  0  3  0  0  1  0  0]
 [ 0  3  0  3  0  1  0  0]
 [ 0  0  0  0  3  4  0  0]
 [ 0  1  0  0  0 12  0  0]
 [ 0  0  0  0  0  5  9  0]
 [ 0  1  0  0  0  0  0  0]]

Classification Report:
                     precision    recall  f1-score  support
mildly negative       0.000000  0.000000  0.000000      0.0
mildly positive       0.000000  0.000000  0.000000      3.0
moderately negative   1.000000  0.600000  0.750000      5.0
moderately positive   1.000000  0.428571  0.600000      7.0
negative              1.000000  0.428571  0.600000      7.0
neutral               0.461538  0.923077  0.615385     13.0
positive              1.000000  0.642857  0.782609     14.0
strong positive       0.000000  0.000000  0.000000      1.0
accuracy              0.600000  0.600000  0.600000      0.6
macro avg             0.557692  0.377885  0.418499     50.0
weighted avg          0.780000  0.600000  0.622130     50.0


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.